// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCoiAX_mckZTeDOPo073JSnvSgUDXn1o',
    appId: '1:493159430521:web:84be9b8ea2186c7a9dd7a8',
    messagingSenderId: '493159430521',
    projectId: 'pace-test-348c2',
    authDomain: 'pace-test-348c2.firebaseapp.com',
    storageBucket: 'pace-test-348c2.appspot.com',
    measurementId: 'G-N47P01BK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCelUKVRS-gmdy2_vlrBftHTOgmnkSvxOk',
    appId: '1:493159430521:android:95177956a582a8ae9dd7a8',
    messagingSenderId: '493159430521',
    projectId: 'pace-test-348c2',
    storageBucket: 'pace-test-348c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5LR66rhmJVOD5HjheYpoPdsXnPSm9760',
    appId: '1:493159430521:ios:4f0537f8cbdfb5ec9dd7a8',
    messagingSenderId: '493159430521',
    projectId: 'pace-test-348c2',
    storageBucket: 'pace-test-348c2.appspot.com',
    androidClientId: '493159430521-8ka61772dkd5fa2pu1iidu01i7c2vtr1.apps.googleusercontent.com',
    iosClientId: '493159430521-r1plt9dv5tkbm96270v1hi8377edei78.apps.googleusercontent.com',
    iosBundleId: 'com.example.paceApplicationFb',
  );
}
