enum Permissions {
  //, , , , ]
  none(""),
  addCar("add_car"),
  addInventory("add_inventory"),
  addJob("add_job"),
  addPermission("add_permision"),
  addRole("add_role"),
  addTask("add_task"),
  addUser("add_user"),
  approvedCar("approved_car"),
  approvedTask("approved_task"),
  collaborateOnMicrosoftWhiteboard("collaborate_on_microsoft_whiteboard"),
  deleteInventory("delete_inventory"),
  deleteJob("delete_job"),
  deletePermision("delete_permision"),
  deleteRole("delete_role"),
  deleteTask("delete_task"),
  deleteUser("delete_user"),
  editInventory("edit_inventory"),
  edit_job("edit_job"),
  edit_permision("edit_permision"),
  edit_profile("edit_profile"),
  edit_role("edit_role"),
  edit_task("edit_task"),
  edit_user("edit_user"),
  export_inventory("export_inventory"),
  export_job("export_job"),
  export_permision("export_permision"),
  export_role(""),
  export_task(""),
  export_tasks_in_pdf(""),
  export_user(""),
  rejected_car(""),
  rejected_task(""),
  self_assign_a_task(""),
  share_car(""),
  admin(""),
  review_tasks(""),
  view_car(""),
  view_dashboard_with_graphs(""),
  view_inventory(""),
  view_inventory_detail(""),
  view_job(""),
  view_notifications(""),
  view_past_cars(""),
  view_permision(""),
  view_profile(""),
  view_rejected_tasks(""),
  view_role(""),
  view_task(""),
  view_user("");

  final String value;
  // can use named parameters if you want
  const Permissions(this.value);
}
